# Generated by Django 3.2.8 on 2022-04-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('Model', models.CharField(max_length=255, verbose_name='Model')),
                ('Sales_in_thousands', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Sales_in_thousands')),
                ('Price_in_thousands', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Price_in_thousands')),
                ('Engine_size', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Engine_size')),
                ('Horsepower', models.IntegerField(verbose_name='Horsepower')),
                ('Fuel_capacity', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Fuel_capacity')),
                ('Fuel_efficiency', models.IntegerField(verbose_name='Fuel_efficiency')),
            ],
        ),
    ]
